<?php

use Illuminate\Database\Seeder;

class VesselTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('vessel_types')->delete();

        DB::table('vessel_types')->insert([
            ['name' => 'Accommodation Vessel'],
            ['name' => 'Anchor Handling Tug'],
            ['name' => 'Asphalt/Bitumen Tanker'],
            ['name' => 'Breakbulk Freighter'],
            ['name' => 'Breakbulk/Container'],
            ['name' => 'Bulk Carrier'],
            ['name' => 'Bulk Carrier Barge'],
            ['name' => 'Bulk Cement Barge'],
            ['name' => 'Bulk Woodchip Carrier'],
            ['name' => 'Bulk/Dry Cargo Carrier'],
            ['name' => 'Bunker Barge'],
            ['name' => 'Cable Layer'],
            ['name' => 'Car Carrier'],
            ['name' => 'Cargo Barge'],
            ['name' => 'Catamaran Utility'],
            ['name' => 'Cement Carrier'],
            ['name' => 'Chemical Tanker'],
            ['name' => 'Chemical/Products Tanker'],
            ['name' => 'Clean Oil Barge'],
            ['name' => 'Coastal Tanker'],
            ['name' => 'Combi Carrier'],
            ['name' => 'Conbulker'],
            ['name' => 'Container Feeder'],
            ['name' => 'Container Ship'],
            ['name' => 'Crane Vessel'],
            ['name' => 'Crew/Supply Vessel'],
            ['name' => 'Crude Oil Tanker'],
            ['name' => 'Crude Oil/Products Carrier'],
            ['name' => 'Crude Oil/Products Tanker'],
            ['name' => 'Crude/Chem/Products Tanker'],
            ['name' => 'Cruise Ship'],
            ['name' => 'DH Oil & Product Tanker'],
            ['name' => 'DH Oil Carrier'],
            ['name' => 'DH Oil Tanker'],
            ['name' => 'Diving Support Vessel'],
            ['name' => 'Drilling Rig'],
            ['name' => 'Drilling Ship'],
            ['name' => 'Drillship'],
            ['name' => 'Dry Cargo Barge'],
            ['name' => 'Dynamic Semisubmersible'],
            ['name' => 'Excurison'],
            ['name' => 'Factory Stern Trawler'],
            ['name' => 'Factory Trawler'],
            ['name' => 'Ferry/Passenger Ship'],
            ['name' => 'Fish Carrier'],
            ['name' => 'Fishing Vessel'],
            ['name' => 'Floating Storage Regas Unit'],
            ['name' => 'FPSO'],
            ['name' => 'Freezer Longliner'],
            ['name' => 'Freight Barge'],
            ['name' => 'Freighter'],
            ['name' => 'Fruit Juice Carrier'],
            ['name' => 'G.C. (Container)'],
            ['name' => 'Gas Carrier'],
            ['name' => 'General Cargo Ship'],
            ['name' => 'Heavy Load Carrier'],
            ['name' => 'Heavy-Lift'],
            ['name' => 'Heavy-load Semisubmersible'],
            ['name' => 'Hopper Barge'],
            ['name' => 'Hopper/Suction Dredge'],
            ['name' => 'Hybrid Reefer'],
            ['name' => 'Ice Breaker'],
            ['name' => 'Industrial Barge'],
            ['name' => 'Livestock Carriers'],
            ['name' => 'LNG Tanker'],
            ['name' => 'Log Carrier'],
            ['name' => 'Logistics Vessel'],
            ['name' => 'LPG Tanker'],
            ['name' => 'LPG/LNG Tanker'],
            ['name' => 'Manned Hopper Barge'],
            ['name' => 'Manned Tank Barge'],
            ['name' => 'MODU'],
            ['name' => 'Moored Semisubmersible'],
            ['name' => 'Motor Yacht'],
            ['name' => 'Multi Purpose Cargo Ship'],
            ['name' => 'Multi-Purpose Carrier'],
            ['name' => 'Multipurpose Dry Cargo'],
            ['name' => 'Multipurpose Dry/Container'],
            ['name' => 'Multipurpose Platform Suppl'],
            ['name' => 'Multipurpose Tween Decker'],
            ['name' => 'OBO'],
            ['name' => 'Offshore Support Vessel'],
            ['name' => 'Offshore Tug/Supply Vessel'],
            ['name' => 'Oil Chemical Tanker Type II'],
            ['name' => 'Oil Tanker'],
            ['name' => 'Oil/Bitumen Tanker'],
            ['name' => 'Oil/Chemical Tanker'],
            ['name' => 'Oil/Water Tanker'],
            ['name' => 'Open Hatch Cargo Vessel'],
            ['name' => 'Open Hatch/Pitch'],
            ['name' => 'Ore Carrier'],
            ['name' => 'Ore/Coal Carrier'],
            ['name' => 'Other Cargo Ship'],
            ['name' => 'Other Cargo/Container'],
            ['name' => 'Panmax Bulker'],
            ['name' => 'Passenger Ship'],
            ['name' => 'Passenger/Freight'],
            ['name' => 'PCTC'],
            ['name' => 'Pilot Vessel'],
            ['name' => 'Pipe Layer'],
            ['name' => 'Platform Supply'],
            ['name' => 'Products Tanker'],
            ['name' => 'Public Vessel'],
            ['name' => 'Pure Car Carrier'],
            ['name' => 'Purse Seiner'],
            ['name' => 'Pushboat'],
            ['name' => 'Pusher Tug'],
            ['name' => 'Recreational'],
            ['name' => 'Reefer Vessel'],
            ['name' => 'Refrigerated Cargo Ship'],
            ['name' => 'Research Survey Vessel'],
            ['name' => 'Ro-Ro Vessel'],
            ['name' => 'Ro-Ro/Docking Vessel'],
            ['name' => 'RoCon'],
            ['name' => 'Sailing Passenger Vessel'],
            ['name' => 'Seafood Processor'],
            ['name' => 'Seismec Survey'],
            ['name' => 'Sheerleg Pontoon'],
            ['name' => 'Shuttle Tanker'],
            ['name' => 'Subsea Construction'],
            ['name' => 'Tank Barge'],
            ['name' => 'Tanker Oil/Chemical'],
            ['name' => 'Tanker, Self-propelled'],
            ['name' => 'Tankship'],
            ['name' => 'Towing Vessel'],
            ['name' => 'Trailing Suction Dredge'],
            ['name' => 'Training Vessel'],
            ['name' => 'Trenching Support Vessel'],
            ['name' => 'Tugboat'],
            ['name' => 'Unmanned Hopper Barge'],
            ['name' => 'Unmanned Tank Barge'],
            ['name' => 'USCG Lightship'],
            ['name' => 'Vehicles Carrier'],
            ['name' => 'VLCC'],
            ['name' => 'Water Tank Vessel'],
            ['name' => 'Wood Chips Carrier'],
            ['name' => 'Yacht']
        ]);
    }
}
